# Docker Compose 파일 형식 버전을 지정합니다. '3.8'을 사용하는 것이 일반적입니다.
version: '3.8'

# 실행할 서비스(컨테이너)들을 정의하는 부분입니다.
services:
  # 서비스의 이름을 'web'으로 정합니다. (원하는 이름으로 변경 가능)
  web:
    # 사용할 도커 이미지를 지정합니다. 과제 요구사항에 맞게 httpd:2.4.59로 설정합니다.
    image: httpd:2.4.59

    # 컨테이너의 이름을 'my-apache-app'으로 고정합니다.
    container_name: my-apache-app

    # 포트 연결(포워딩)을 설정합니다.
    # "내컴퓨터포트:컨테이너포트" 형식입니다.
    # 내 컴퓨터의 8080 포트로 접속하면 컨테이너의 80 포트로 연결됩니다.
    ports:
      - "8080:80"

    # 볼륨 연결(마운트)을 설정합니다. 이 부분이 가장 중요합니다.
    # "내컴퓨터경로:컨테이너경로" 형식입니다.
    volumes:
      # 1. 내 컴퓨터의 ./htdocs 폴더를 컨테이너의 웹 루트 디렉토리에 연결
      - ./htdocs:/usr/local/apache2/htdocs/
      # 2. 내 컴퓨터의 ./conf/httpd.conf 파일을 컨테이너의 설정 파일 위치에 연결
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf

    # 컨테이너가 항상 재시작되도록 설정하여 안정성을 높입니다.
    restart: always