version: '3.8'
services:
  web:
    build: .
    container_name: my-apache-app
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: always